name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_GA_MEASUREMENT_ID: ${{ secrets.VITE_GA_MEASUREMENT_ID }}
          VITE_FB_PIXEL_ID: ${{ secrets.VITE_FB_PIXEL_ID }}
          VITE_ENABLE_ANALYTICS: "true"
      - name: Debug Env Variables
        run: |
          echo "API URL prefix: ${VITE_API_URL:0:15}..." # Show just the beginning for security
          echo "GA Measurement ID set: $([[ -n $VITE_GA_MEASUREMENT_ID ]] && echo 'Yes' || echo 'No')"
          echo "FB Pixel ID set: $([[ -n $VITE_FB_PIXEL_ID ]] && echo 'Yes' || echo 'No')"

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /var/www/natura/new-dist/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p /var/www/natura/{dist,new-dist,old-dist}

            # Atomic deployment - for zero downtime
            if [ -d "/var/www/natura/dist" ]; then
              mv /var/www/natura/dist /var/www/natura/old-dist
            fi
            mv /var/www/natura/new-dist /var/www/natura/dist

            # Optional - cleanup old build after successful deploy
            rm -rf /var/www/natura/old-dist
